BACKUP_FILENAME_PREFIX: str = "BACKUP"
BACKUP_FILENAME_FORMAT: str = "%Y-%m-%d-%H:%M"
BACKUP_FILE_EXTENSION: str = ".zip"
DEFAULT_BACKUP_CRON: str = "0 3 * * *"
DEFAULT_MAX_BACKUPS: int = 5
DEFAULT_PORT: int = 8989
DOWNLOAD_TOTP_WINDOW_SECONDS: int = 30
SESSION_SIGNER_SEPARATOR: str = "."
